const DECK_START_SIZE = 3;
const MAXIMUM_NUMBER_PLAYERS = 4;
const DEFAULT_ACCENT_COLOR = '#3f51b5';
const SYSTEM_PLAYER_DISPLAY_NAME = 'Sistema';
const FEATURE = 'feature';
const THEME = 'theme';

export { DECK_START_SIZE, MAXIMUM_NUMBER_PLAYERS, DEFAULT_ACCENT_COLOR, SYSTEM_PLAYER_DISPLAY_NAME, FEATURE, THEME };
