const DECK_START_SIZE = 3;
const MAXIMUM_NUMBER_PLAYERS = 4;
const DEFAULT_ACCENT_COLOR_CODE = '#3f51b5';
const SYSTEM_PLAYER_DISPLAY_NAME = 'Sistema';

export { DECK_START_SIZE, MAXIMUM_NUMBER_PLAYERS, DEFAULT_ACCENT_COLOR_CODE, SYSTEM_PLAYER_DISPLAY_NAME };
