const DECK_START_SIZE = 3;
const MAXIMUM_NUMBER_PLAYERS = 4;
const DEFAULT_ACCENT_COLOR_CODE = '#3f51b5';
const NEUTRAL_COLOR_CODE = '#64748B';
const SYSTEM_PLAYER_DISPLAY_NAME = 'Sistema';
const TILE_SIZES = ['6', '8', '10', '12', '14', '16', '18'];
const DEFAULT_TILE_SIZE = '6';

export { DECK_START_SIZE, MAXIMUM_NUMBER_PLAYERS, DEFAULT_ACCENT_COLOR_CODE, NEUTRAL_COLOR_CODE, SYSTEM_PLAYER_DISPLAY_NAME, TILE_SIZES, DEFAULT_TILE_SIZE };
